### PR TITLE
RHMAP-9304: Add i18n support in formbuilder.js

### PR DESCRIPTION
**Pull request by tagoh**
This change is to add i18n support in formbuilder.js and some tasks in Gruntfile. `grunt potupload` to update the POT file from the latest code and upload it to the Zanata as usual as fh-ngui and fh-fhc does, and `grunt updatetrans` to pull translations from the Zanata and update formbuilder-lang-*.json according to the PO files.

To accomplish i18n support related to the formbuilder, some updates in fh-ngui is also required to load formbuilder-lang-*.json and for other UI coming from fh-ngui.
So this PR would be supposed to fix the part of RHMAP-9304.

### CODE REVIEW

**Comment by tagoh** [comment]
Any chance to get this reviewed?

**Comment by jasonmadigan** [comment]
@witmicko you might take a look?

**Comment by tagoh** [comment]
any updates on this?

**Comment by camilamacedo86** [comment]
Hi @witmicko ,

I am trying to test it following the steps in the README. 

1.npm install
2.bower install
3.grunt watch
4.open example/index.html and you're all set!

However, using the master branch the result is a blank as following. 

screen shot 2018-06-29 at 14 04 18

I think the doc is outdated. Please, could you help me telling how should we test/run it?

**Comment by camilamacedo86** [comment]
Tested performed with success. See the https://github.com/fheng/fh-ngui/pull/1531. Then we will be able to merge this PR.

**Pull request merged**
